module.exports = [
  {
    search_id: "unique_id 1",
    type: "family",
    price_min: 10000,
    price_max: 20000,
    bedroom: 2,
    washroom: 2,
    area_min: 1000,
    area_max: 2000,
    area: "Mirpur",
    zone: "Dhaka",
    facilities: ["wifi", "parking"],
    star_points: ["nearby_school", "nearby_hospital"],
  },
  {
    search_id: "unique_id 2",
    type: "family",
    price_min: 10000,
    price_max: 20000,
    bedroom: 2,
    washroom: 2,
    area_min: 1000,
    area_max: 2000,
    area: "Mirpur",
    zone: "Dhaka",
    facilities: ["wifi", "parking"],
    star_points: ["nearby_school", "nearby_hospital"],
  },
];
